# Generated by Django 5.2.13 on 2026-06-06 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacaoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, choices=[('V', 'Vitória'), ('D', 'Derrota'), ('E', 'Empate')], max_length=1, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AG', 'Agendada'), ('EA', 'Em andamento'), ('FI', 'Finalizada')], default='AG', max_length=2)),
                ('jogadores', models.ManyToManyField(through='matches.ParticipacaoPartida', to=settings.AUTH_USER_MODEL)),
                ('rodada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='tournaments.rodada')),
            ],
        ),
        migrations.AddField(
            model_name='participacaopartida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='matches.partida'),
        ),
    ]
