# Generated by Django 5.2.13 on 2026-06-10 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_participacaopartida_jogador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacaopartida',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
