# Generated by Django 5.2.13 on 2026-06-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_participacaopartida_jogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='status',
            field=models.CharField(choices=[('AG', 'Agendada'), ('EA', 'Em andamento'), ('FI', 'Finalizada')], default='EA', max_length=2),
        ),
    ]
