# Generated by Django 5.2.13 on 2026-06-06 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.CharField(choices=[('nissa', 'Nissa')], default='nissa', max_length=20)),
                ('email_verificado', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='core.cidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario_curtido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_recebidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_que_curtiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_feitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario_que_curtiu', 'usuario_curtido'), name='unique_profile_like')],
            },
        ),
    ]
