# Generated by Django 5.2.13 on 2026-06-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('nissa', 'Nissa'), ('niv', 'Niv-Mizzet')], default='nissa', max_length=20),
        ),
    ]
