# Generated by Django 5.2.13 on 2026-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('Atraxa', 'Atraxa'), ('chandra', 'Chandra'), ('driade', 'Driade'), ('gideon', 'Gideon'), ('gisha', 'Gisha'), ('jace', 'Jace'), ('lilia', 'Lilia'), ('nissa', 'Nissa'), ('niv', 'Niv-Mizzet'), ('tishana', 'Tishana'), ('xavier_sal', 'Xavier-Sal')], default='Atraxa', max_length=20),
        ),
    ]
