# Generated by Django 5.2.13 on 2026-06-06 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('numero_maximo_participantes', models.PositiveIntegerField(default=20)),
                ('codigo_inscricao', models.CharField(editable=False, max_length=10)),
                ('inscricao_publica', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('CA', 'Casual'), ('CO', 'Competitivo')], default='CO', max_length=2)),
                ('formato_torneio', models.CharField(choices=[('SWISS', 'Sistema Suiço'), ('SINGLE_ELIM', 'Eliminação Simples')], max_length=20)),
                ('status', models.CharField(choices=[('CRIADO', 'Criado'), ('ABERTA', 'Aberto'), ('FECHADA', 'Fechado'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='CRIADO', max_length=21)),
                ('formato_jogo', models.CharField(choices=[('ST', 'Standard'), ('CM', 'Commander'), ('MO', 'Modern'), ('PI', 'Pioneer'), ('DR', 'Draft')], default='CM', max_length=2)),
                ('numero_rodadas', models.PositiveIntegerField()),
                ('data_inicio', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torneios', to='core.cidade')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torneios_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('FI', 'Finalizada')], default='AB', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodadas', to='tournaments.torneio')),
            ],
            options={
                'ordering': ['-numero'],
                'unique_together': {('torneio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='TorneioParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Rejeitada')], default='PE', max_length=2)),
                ('pontos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='tournaments.torneio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('torneio', 'jogador'), name='participante_unico')],
            },
        ),
    ]
