# Generated by Django 5.2.13 on 2026-06-06 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='torneios', to='core.cidade'),
        ),
    ]
