# Generated by Django 5.2.13 on 2026-06-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_torneio_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='local',
            field=models.CharField(default='none', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneio',
            name='valor_inscricao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
