# Generated by Django 5.2.13 on 2026-06-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_torneio_local_torneio_valor_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='premiacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
