# Generated by Django 5.2.13 on 2026-06-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_torneio_premiacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='inscricao_publica',
            field=models.BooleanField(default=True),
        ),
    ]
