# Generated by Django 5.2.13 on 2026-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_torneio_inscricao_publica'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='imagem_fundo',
            field=models.CharField(choices=[('dinos', 'Dissa')], default='dino', max_length=20),
            preserve_default=False,
        ),
    ]
