# Generated by Django 5.2.13 on 2026-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_torneio_imagem_fundo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='valor_inscricao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
