# Generated by Django 5.2.13 on 2026-06-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_torneio_valor_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='imagem_fundo',
            field=models.CharField(choices=[('monumento_magic', 'Monumento')], max_length=20),
        ),
    ]
