# Generated by Django 5.2.13 on 2026-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_torneio_imagem_fundo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='imagem_fundo',
            field=models.CharField(blank=True, choices=[('cidade_vermelha', 'Cidade Vermelha'), ('dinos_magic', 'Dinos Magic'), ('lobinho_magic', 'Sienna'), ('monumento_magic', 'Monumento'), ('pretos', 'Pretos')], max_length=20, null=True),
        ),
    ]
